version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:4200
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example_db
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  