version: '3.8'

services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
  